# Generated by Django 2.0 on 2018-01-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
    ]
